#!/usr/bin/env bash

python3 /home/opc/project/guestPW.py > /home/opc/project/guestPassword.txt
str="Wireless 3rd party access information"
while [[ $(head -n 1 /home/opc/project/guestPassword.txt) != "$str" ]]
do
	python3 /home/opc/project/guestPW.py > /home/opc/project/guestPassword.txt
done



sed -i "1s/^/\`\`\`\n/" /home/opc/project/guestPassword.txt
echo "\`\`\`" >> "/home/opc/project/guestPassword.txt"
curl -X POST -H --silent --data-urlencode "payload={\"text\": \"$(cat /home/opc/project/guestPassword.txt | sed "s/\"/'/g")\"}" https://hooks.slack.com/services/<slack's api key>
password=$(head -n 5 /home/opc/project/guestPassword.txt | tail -n +5 | cut -d ' ' -f2)	
curl -X POST -H 'Content-type: application/json' --data '{"text": "'"$password"'"}' https://hooks.slack.com/services/<slack's api key>
