#!/usr/bin/env bash

python3 /home/opc/project/guestPW.py > /home/opc/project/guestPassword.txt
str="Wireless 3rd party access information"
while [[ $(head -n 1 /home/opc/project/guestPassword.txt) != "$str" ]]
do
	python3 /home/opc/project/guestPW.py > /home/opc/project/guestPassword.txt
done

#if ! [ -s /home/opc/project/guestPassword.txt ]
#then
	
#	echo "Error retrieving guest wifi password. Trying again..." >> "/home/opc/project/guestPassword.txt"
#	curl -X POST -H --silent --data-urlencode "payload={\"text\": \"$(cat /home/opc/project/guestPassword.txt | sed "s/\"/'/g")\"}" https://hooks.slack.com/services/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
#	curl -X POST -H --silent --data-urlencode "payload={\"text\": \"$(cat /home/opc/project/guestPassword.txt | sed "s/\"/'/g")\"}" https://hooks.slack.com/services/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
#else

sed -i "1s/^/\`\`\`\n/" /home/opc/project/guestPassword.txt
echo "\`\`\`" >> "/home/opc/project/guestPassword.txt"
curl -X POST -H --silent --data-urlencode "payload={\"text\": \"$(cat /home/opc/project/guestPassword.txt | sed "s/\"/'/g")\"}" https://hooks.slack.com/services/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
password=$(head -n 5 /home/opc/project/guestPassword.txt | tail -n +5 | cut -d ' ' -f2)	
curl -X POST -H 'Content-type: application/json' --data '{"text": "'"$password"'"}' https://hooks.slack.com/services/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

#	curl -X POST -H --silent --data-urlencode "payload={\"text\": \"$(cat /home/opc/project/guestPassword.txt | sed "s/\"/'/g")\"}" https://hooks.slack.com/services/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
#	password=$(head -n 5 /home/opc/project/guestPassword.txt | tail -n +5 | cut -d ' ' -f2)	
#	curl -X POST -H 'Content-type: application/json' --data '{"text": "'"$password"'"}' https://hooks.slack.com/services/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
#fi
#curl -F file=@guestPassword.txt -F channels=guest-wifi -H "Authorization: Bearer xoxp-452578312773-452627489045-741724501968-2a751adba30b18cd9baa9d31a7bd9932" https://slack.com/api/files.upload
